main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/my_vote', views.my_vote, name='my_vote'),
]

muje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.conf import settings
from accounts.models import User
# Create your models here.
class Genre(models.Model):
    name = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews', blank=True)

class Movie_data(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    vote_average = models.FloatField()
    release_date = models.DateField()
    poster_path = models.TextField()
    backdrop_path = models.TextField()
    video = models.TextField()
    genre_ids = models.ManyToManyField(Genre)
    my_vote = models.IntegerField(null=True)

class Combinding(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST, require_GET, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required

from movies.models import Movie_data
# Create your views here.

@require_safe
def index(request):
    
    movie_data_all = Movie_data.objects.all()

    context = {
        'movie_data_all': movie_data_all,
    }

    return render(request, 'movies/index.html', context)

@login_required
def detail(request, pk):

    movie_data = get_object_or_404(Movie_data, pk=pk)
    star = []
    star_fill = []
    star_half = []

    for i in range(int(movie_data.vote_average) // 2):
        star_fill.append(1)
    
    if int(movie_data.vote_average) % 2 == 1:
        star_half.append(1)

    for i in range(5-len(star_fill)-len(star_half)):
        star.append(1)

    context = {
        'movie_data': movie_data,
        'star': star,
        'star_fill': star_fill,
        'star_half': star_half,
    }

    return render(request, 'movies/detail.html', context)

@login_required
@require_POST
def my_vote(request, pk):
    
    movie_data = get_object_or_404(Movie_data, pk=pk)
    movie_data.my_vote = request.POST['my_vote']

    movie_data.save()
    return redirect('movies:detail', pk)

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
    <div style="background: black">
        <header class="" >
            <div style="background-image: url('https://image.tmdb.org/t/p/w400//{{movie_data.backdrop_path}}'); background-repeat : no-repeat; background-size : cover;">
            <div class="bg-dark "style="--bs-bg-opacity: .9;">
            <div class="" style="text-align: center; width: 100%">
                <img src="https://image.tmdb.org/t/p/w300/{{movie_data.poster_path}}" class="" alt="..." width="300" style="margin-top: 30px">
                <div class="d-flex justify-content-center small text-warning mb-2" style="margin-top: 20px">
                    {% for i in star_fill %}
                        <div class="bi-star-fill"></div>
                    {% endfor %}
                    {% for i in star_half %}
                        <div class="bi-star-half"></div>
                    {% endfor %}
                    {% for i in star %}
                        <div class="bi-star"></div>
                    {% endfor %}
                </div>
                <div class="text-center" style="margin-bottom: 20px">
                    <h2 class="fs-2 fw-bolder text-light">{{movie_data.title}}</h2>
                </div>
                <form action="{% url 'movies:my_vote' movie_data.pk %}" method="POST" class="d-flex justify-content-center">
                    {% csrf_token %}
                    <select name="my_vote" class="form-select form-select-sm bg-secondary text-white center" aria-label=".form-select-sm example" style="width: 100px;">
                        {% if movie_data.my_vote == None %}
                            <option value="None" selected>점수</option>
                        {% else %}
                            {% if movie_data.my_vote == 0 %}
                                <option value="0" selected>점수</option>
                            {% else %}
                                <option selected>{{movie_data.my_vote}}</option>
                            {% endif %}
                        {% endif %}
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="0">취소</option>
                    </select>
                    <input type="submit" class="btn btn-secondary" value="등록" style="height: 70%; margin-left: 15px">
                <form>
            </div>
            <div>.</div>
        </header>
        <section style="margin-top: 30px">
            <div class="container">
                <div class="text-center">
                    <h2 class="text-light" style="font-family: 'BMEuljiro10yearslater'; margin-bottom: 20px" >Story</h2>
                    <h3 class="section-subheading text-muted " style="width: 800px; margin: 0 auto; font-family: 'KoPubDotumMedium';">{{movie_data.overview}}</h3>
                </div>
                <div class="text-center" style="margin-top: 30px">
                    <h2 class="text-light" style="font-family: 'BMEuljiro10yearslater'; margin-bottom: 20px" >Trailer</h2>
                    <iframe   
                    class="embed-responsive-item"
                    src='https://www.youtube.com/embed/{{ movie_data.video }}'
                    frameborder="0" 
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
                    allowfullscreen
                    style="width: 800px; height: 500px"
                    ></iframe>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
<!-- Header-->
    <div style="background: black">
    <div style="background-image: url('https://s3-us-west-2.amazonaws.com/prd-rteditorial/wp-content/uploads/2018/03/13153742/RT_300EssentialMovies_700X250.jpg'); height: 300px; background-repeat : no-repeat; background-size : cover;">
    
    </div>
    <!-- Section-->
    <section class="py-5" sty>
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for movie_data in movie_data_all%}
                <a href="{% url 'movies:detail' movie_data.pk %}" class="text-decoration-none">
                <div class="col mb-5">
                    <div class="card" style="height: 380px">
                        <img class="card-img-top" src="https://image.tmdb.org/t/p/w300/{{movie_data.poster_path}}" alt="..." style="min-height: 100%"/>
                    </div>
                </div>
                </a>
                {% endfor %}
            </div>    
        </div>
    </section>
    </div>
{% endblock %}