community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/comment/create/', views.comments_create, name='comments_create'),
    path('onair/', views.onair, name='onair'),
    path('recommend/', views.recommend, name="recommend"),
    path('choose/', views.choose, name="choose"),
    path('likechoose/<username>/<int:id>/', views.like_choose, name="like_choose"),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/my_vote', views.my_vote, name='my_vote'),
]

muje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Community_review(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)


class Community_comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review_id = models.ForeignKey(Community_review, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

community/forms.py
from django import forms
from django.db.models import fields
from .models import Community_review, Community_comment
from accounts.models import User

class Community_reviewForm(forms.ModelForm):
    class Meta:
        model = Community_review
        fields = ('title', 'content',)

class Community_commentForm(forms.ModelForm):
    class Meta:
        model = Community_comment
        fields = ('content',)

community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST, require_GET, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required
from .models import Community_review, Community_comment
from movies.models import Genre, Movie_data
from accounts.models import User
from .forms import Community_reviewForm, Community_commentForm
from bs4 import BeautifulSoup
import requests
import random
# Create your views here.

@require_safe
def index(request):
    
    community_reviews = Community_review.objects.all()

    context = {
        'community_reviews': community_reviews,
    }

    return render(request, 'community/index.html', context)

@login_required
def detail(request, pk):

    community_review = get_object_or_404(Community_review, pk=pk)

    community_comment = Community_comment.objects.filter(review_id=community_review.pk)
    
    community_commentForm = Community_commentForm()

    context = {
        'community_review': community_review,
        'community_comment': community_comment,
        'community_commentForm': community_commentForm,
    }

    return render(request, 'community/detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = Community_reviewForm(request.POST)

        if form.is_valid():
            community_review = form.save(commit=False)
            community_review.user_id = request.user
            community_review.save()
            return redirect('community:detail', community_review.pk)

    else:
        form = Community_reviewForm()
    
    context = {
        'form': form,
    }

    return render(request, 'community/form.html', context)

@login_required
@require_POST
def delete(request, pk):
    
    community_review = get_object_or_404(Community_review, pk=pk)
    community_review.delete()

    return redirect('community:index')

@login_required
@require_POST
def comments_create(request, pk):
    
    community_review = get_object_or_404(Community_review, pk=pk)
    
    community_commentForm = Community_commentForm(request.POST)
    
    if community_commentForm.is_valid():
        community_comment = community_commentForm.save(commit=False)
        community_comment.review_id = community_review
        community_comment.user_id = community_review.user_id
        community_comment.save()
        return redirect('community:detail', community_review.pk)

    return redirect('community:index')

@login_required
@require_POST
def comment_delete(request, pk):
    
    community_comment = get_object_or_404(Community_comment, pk=pk)
    community_comment.delete()

    return redirect('community:index')

def onair(request):
    url = 'https://movie.naver.com/movie/running/current.naver'
    res = requests.get(url)
    data = BeautifulSoup(res.text, 'html.parser')
    uls = data.find("ul", class_="lst_detail_t1").find_all("dt", class_="tit")
    img = data.find("ul", class_="lst_detail_t1").find_all("img")
    movies = []
    for i, title in enumerate(uls):
        temp = []
        tt = " ".join(title.get_text().split()[2:])
        temp.extend([i + 1, tt])
        for j, title in enumerate(img):
            if temp[0] == j+1:
                temp.append(title["src"][:-15])
                break
        movies.append(temp)
    if len(movies) > 18:
        context = {
            'movies':movies[:18],
        }
    else:
        context = {
            'movies':movies,
        }
    return render(request, 'community/onair.html', context)

def choose(request):
    genres = Genre.objects.all()
    profile_user = request.user
    context = {
            'genres':genres,
            'profile_user' : profile_user,
        }
    return render(request, 'accounts/profile.html', context)

def like_choose(request, username, id):
    genres = get_object_or_404(Genre, pk=id)
    if genres.like_users.filter(id=request.user.pk).exists():
        genres.like_users.remove(request.user)
        genres.save()
    else:
        genres.like_users.add(request.user)
        genres.save()
    print(genres.like_users.all())
    return redirect('community:choose')


def recommend(request):
    
    user =  get_object_or_404(User, pk=request.user.id)
    movie_data = Movie_data.objects.all()
    like_genres = user.like_reviews.all()
    genre_dict = {}
    if len(like_genres)> 0:
        for like_genre in like_genres:
            genre_dict[like_genre.id] = []
    my_vote = []
    personal_recommend = []
    for movie in movie_data:
        # print(movie.genre_ids.all())
        if (movie.my_vote != None or 0) and movie.my_vote >=5 :
            my_vote.append(movie)

        for key in genre_dict.keys():
            if movie.genre_ids.filter(id=key):
                genre_dict[key].append(movie)
            
    
    for key, value in genre_dict.items():
        if len(genre_dict[key]) > 6:
            genre_dict[key] = random.sample(genre_dict[key], 6)
        
    if len(my_vote) != 0:
        id_list = {}
        for vote in my_vote:
            k = vote.genre_ids.filter()
            for i in k:
                id_list[i.pk] = 1
        for movie in movie_data:
            for key in id_list.keys():
                if movie.genre_ids.filter(id=key) and movie.vote_average > 6:
                    personal_recommend.append(movie)
    # my_vote = movie_data.my_vote
    if len(personal_recommend) > 6:
            personal_recommend = random.sample(personal_recommend, 6)

    context = {
        'like_genres': like_genres, 
        'range': len(like_genres) + len(personal_recommend),
        'genre': genre_dict,
        'my_vote':my_vote,
        'personal_recommend':personal_recommend,
    }

    return render(request, 'community/recommend.html', context)

community/templates/community/choose.html
  <h3 class="text-center">선호하는 장르를 선택해주세요!</h3>
  <hr>
  <div class="row m-0 my-5 row-cols-1 row-cols-md-6 g-3">
  {% for genre in genres %}
    {% comment %} {{genre}}
    {{genre.id}}
    {{genre.name}}
    {{user}} {% endcomment %}
    {% comment %} {% for genreaaa in genre.like_users %}{{genreaaa}}{% endfor %} {% endcomment %}
    {% comment %} {{genre.like_users}} {% endcomment %}
    
    <form action="{% url 'community:like_choose' user genre.id  %}" method="post">
      {% csrf_token %}
      {% if user in genre.like_users.all %}
        <button type="submit" class="btn btn-info btn-lg btnsize" id="inlineCheckbox{{ids.id}}" autocomplete="on">
        {{genre.name}}</button>
      {% else %}
        <button type="submit" class="btn btn-light btn-lg btnsize" id="inlineCheckbox{{ids.id}}" autocomplete="on">
        {{genre.name}}</button>
      {% endif %}
    </form>
  {% endfor %}
  </div>
  <style>
    .btnsize {width: 100%;}
  </style>
      <hr>

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
  <div class="d-flex justify-content-center" style="margin-top: 20px">
  <div class="center-block" style="background: #2c3034; width: 800px; border: 1px solid #373b3e; padding: 20px">
  <div class="d-flex justify-content-between">
    <h1>{{ community_review.title }}</h1>
    <div class="d-flex">
    <p style="margin-top: 10px">작성자 : {{ community_review.user_id }}</p>
    {% if user == community_review.user_id %}
      <form action="{% url 'community:delete' community_review.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-secondary" value="삭제" style="height: 70%; margin-left: 15px">
      </form>
    {% endif %}
    </div>
  </div>
  
  <hr>
  
  <p>{{ community_review.content }}</p>
  <hr>
  {% for comment in community_comment %}
    <div class="d-flex">
      <div style="margin: 0 10px">{{comment.user_id}} : </div>
      <p>{{comment.content}}</p>
      <div style="margin: 0 10px">작성일 : </div>
      <p>{{comment.created_at}}</p>
      {% if user == comment.user_id %}
        <form action="{% url 'community:comment_delete' comment.pk%}" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-secondary" value="삭제" style="height: 70%; margin-left: 15px">
        </form>
      {% endif %}
    </div>
  {% endfor %}
  <div>
  <form class="d-flex justify-content-center" action="{% url 'community:comments_create' community_review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form community_commentForm %}
    <input type="submit" class="btn btn-secondary" value="댓글 등록" style="height: 50%; margin-top: 32px; margin-left: 10px">
  </form>
  </div>
  </div>
{% endblock %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
  <h1>리뷰 등록</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="등록">
  </form>
  <br>
{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}

{% block body %}
  <div style="">
    <div class="position-relative top-0 start-50 translate-middle-x" style="text-align: center; margin-top: 20px; width: 80%; font-family: 'KOTRALEAP';">
      <h2 style="">Community</h2>
      <table class="table table-dark table-striped" style="margin-top: 20px;">
        <thead>
          <tr>
            <th scope="col">글 번호</th>
            <th scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일</th>
          </tr>
        </thead>
        <tbody>
          {% for community_review in community_reviews %}
          
          <tr>
            <th scope="row">{{community_review.pk}}</th>
              <td style = "cursor:pointer;" onClick = "location.href='{% url 'community:detail' community_review.pk %}'">{{community_review.title}}</td>
            <td>{{community_review.user_id}}</td>
            <td>{{community_review.created_at}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <button type="button" class="btn btn-secondary" onclick = "location.href = '{% url 'community:create' %}'">글쓰기</button>
    </div>
  </div>
{% endblock %}

community/templates/community/onair.html
{% extends 'base.html' %}

{% block body %}

<div class="row m-0 my-5 row-cols-1 row-cols-md-6 g-3 text-dark">
  {% for movie in movies %}
    <div class="imgList_{{movie.0}}" data-bs-toggle="modal" data-bs-target="#exampleModal{{movie.0}}">
    <div class="col">
      <div class="card h-100">
        <img src="{{movie.2}}" class="card-img-top" alt="..." width="400">
        <div class="card-body">
          <h5 class="card-title overflow">{{movie.1}}</h5>
          {% comment %} <p class="card-text">{{movie.2}}</p> {% endcomment %}
        </div>
      </div>
    </div>
    </div>


  <div class="modal fade" id="exampleModal{{movie.0}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{movie.1}}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <img src="{{movie.2}}" class="card-img-top" alt="..." >
        </div>
        <div class="modal-footer">
          <button onclick="window.open('https://www.megabox.co.kr/')" class="btn"><img src="../../photo/megabox.png" width="50"></button>
          <button onclick="window.open('https://www.cgv.co.kr/')" type="button" class="btn"><img src="../../photo/cgv.png" width="50"></button>
          <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


<h3>주변 영화관 찾기</h3>
<input hidden=true type="text" id="sample4_postcode" placeholder="우편번호">
<div class="row m-0">
  <input class="col-8 form-control" type="text" oninput="getMap()" style="font-size: 1.8vw;" id="sample4_roadAddress" placeholder="도로명주소">
  <input class="col-4 form-control btn btn-info" type="button" onclick="sample4_execDaumPostcode()" style="font-size: 1.8vw;" value="현재 위치 검색">
</div>
<input hidden=true type="text" id="sample4_jibunAddress" placeholder="지번주소">
<span hidden=true id="guide" style="color:#999;display:none"></span>
<input hidden=true type="text" id="sample4_detailAddress" placeholder="상세주소">
<input hidden=true type="text" id="sample4_extraAddress" placeholder="참고항목">

<div class="mt-3 mb-5" id="map" style="width:100;height:400px;"></div>


<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
  //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.
  function sample4_execDaumPostcode() {
      new daum.Postcode({
          oncomplete: function(data) {
              // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

              // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.
              // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
              var roadAddr = data.roadAddress; // 도로명 주소 변수
              var extraRoadAddr = ''; // 참고 항목 변수

              // 법정동명이 있을 경우 추가한다. (법정리는 제외)
              // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
              if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                  extraRoadAddr += data.bname;
              }
              // 건물명이 있고, 공동주택일 경우 추가한다.
              if(data.buildingName !== '' && data.apartment === 'Y'){
                 extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
              }
              // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
              if(extraRoadAddr !== ''){
                  extraRoadAddr = ' (' + extraRoadAddr + ')';
              }

              // 우편번호와 주소 정보를 해당 필드에 넣는다.
              document.getElementById('sample4_postcode').value = data.zonecode;
              document.getElementById("sample4_roadAddress").value = roadAddr;
              getMap();
              document.getElementById("sample4_jibunAddress").value = data.jibunAddress;
              
              // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.
              if(roadAddr !== ''){
                  document.getElementById("sample4_extraAddress").value = extraRoadAddr;
              } else {
                  document.getElementById("sample4_extraAddress").value = '';
              }

              var guideTextBox = document.getElementById("guide");
              // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.
              if(data.autoRoadAddress) {
                  var expRoadAddr = data.autoRoadAddress + extraRoadAddr;
                  guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';
                  guideTextBox.style.display = 'block';

              } else if(data.autoJibunAddress) {
                  var expJibunAddr = data.autoJibunAddress;
                  guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';
                  guideTextBox.style.display = 'block';
              } else {
                  guideTextBox.innerHTML = '';
                  guideTextBox.style.display = 'none';
              }
          }
          
      }).open();
  }
</script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=2615713b85981a94d5a844d06342ae18&libraries=services"></script>
<script>
  function getMap() {
    // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
    var infowindow = new kakao.maps.InfoWindow({zIndex:1});

    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
      mapOption = {
        center: new kakao.maps.LatLng(100.566826, 126.9786567), // 지도의 중심좌표
        level: 5 // 지도의 확대 레벨
      };  

    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 

    var geocoder = new kakao.maps.services.Geocoder();

    // 주소로 좌표를 검색합니다
    var userAddress = document.getElementById("sample4_roadAddress").value
    geocoder.addressSearch(userAddress, function(result, status) {

      // 정상적으로 검색이 완료됐으면 
      if (status === kakao.maps.services.Status.OK) {

        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new kakao.maps.Marker({
          map: map,
          position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        var infowindow = new kakao.maps.InfoWindow({
          content: '<div style="text-align:center;padding:1px;font-size:12px;">내 위치</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
      }
    }); 

    // 장소 검색 객체를 생성합니다
    var ps = new kakao.maps.services.Places(); 

    // 키워드로 장소를 검색합니다
    var userAddress = document.getElementById("sample4_roadAddress").value
    
    ps.keywordSearch(`${userAddress} 영화관`, placesSearchCB, {category_group_code:'CT1'});

    // 키워드 검색 완료 시 호출되는 콜백함수 입니다
    function placesSearchCB (data, status, pagination) {
      if (status === kakao.maps.services.Status.OK) {

        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
        // LatLngBounds 객체에 좌표를 추가합니다
        var bounds = new kakao.maps.LatLngBounds();

        for (var i=0; i<data.length; i++) {
          displayMarker(data[i]);    
          bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
        }       
      } 
    }

    // 지도에 마커를 표시하는 함수입니다
    function displayMarker(place) {
        
      // 마커를 생성하고 지도에 표시합니다
      var marker = new kakao.maps.Marker({
        map: map,
        position: new kakao.maps.LatLng(place.y, place.x) 
      });

      // 마커에 클릭이벤트를 등록합니다
      kakao.maps.event.addListener(marker, 'click', function() {
        // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
        infowindow.setContent('<div style="padding:5px;font-size:12px;">' + place.place_name + '</div>');
        infowindow.open(map, marker);
        window.open('https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=' + place.place_name);
      });
    }
  };
</script>
<style>
.overflow{
  width        : 180px;     /* 너비는 변경될수 있습니다. */
  text-overflow: ellipsis;  /* 위에 설정한 100px 보다 길면 말줄임표처럼 표시합니다. */
  white-space  : nowrap;    /* 줄바꿈을 하지 않습니다. */
  overflow     : hidden; 
  
}
</style>
{% endblock %}

community/templates/community/recommend.html
{% extends 'base.html' %}

{% block body %}
{% if range > 0  %}
<div clas="mt-5">
  <h3 class="mt-4">개인 추천 영화</h3>
</div> 
          
  <div class="col-12 col-lg-10 text-dark">
    <div class="row mt-5 m-0" style="width: 100%;">
{% for personal in personal_recommend %}
        <div class="col-12 col-md-4 mb-4" style="cursor:pointer;">
          <div class="card h-100 position-relative">
            <div class="imageDiv h-100" >
              <img src="https://image.tmdb.org/t/p/w500{{personal.poster_path}}" class="h-100 card-img-top poster-img" alt="...">
            </div>
            <div class="desc position-absolute w-100 h-100 text-center">
              <div class="position-absolute" OnClick="location.href ='{% url 'movies:detail' personal.pk %}'" style="top: 0; bottom: 3.5rem; width: 100%;"></div>
              <div class="card-title text-truncate"  style="background-color: rgba(86, 189, 190, 0.5); font-size:calc(12px + 1vw); padding: 3vw 0; width: 100%;">{{ personal.title }}</div>
              <div class="text-truncate" style="font-size:calc(8px + 1vw); padding: 1vw 0 0;">평점: {{ personal.vote_average }}</div>
            </div>
          </div>
        </div> 
{% endfor %}
    </div>
  </div>
        
  {% comment %} {% if range > 0  %} {% endcomment %}
    {% for like_genre in like_genres %}
    <div clas="mt-5">
      <h3 class="mt-4">{{like_genre.name}} 추천 영화</h3>
    </div>
      {% for key,values in genre.items %}
        {% if key == like_genre.id %}   
            {% comment %} <div class="wrap">
            <div class="container-fluid"> {% endcomment %}
            {% comment %} <div class="row flex-row flex-nowrap"> {% endcomment %}
            <div class="col-12 col-lg-10 text-dark">
              <div class="row mt-5 m-0" style="width: 100%;">
                {% for value in values %}
                  <div class="col-12 col-md-4 mb-4" style="cursor:pointer;">
                    <div class="card h-100 position-relative">
                      <div class="imageDiv h-100" >
                        <img src="https://image.tmdb.org/t/p/w500{{value.poster_path}}" class="h-100 card-img-top poster-img" alt="...">
                      </div>
                      <div class="desc position-absolute w-100 h-100 text-center">
                        <div class="position-absolute" OnClick="location.href ='{% url 'movies:detail' value.pk %}'" style="top: 0; bottom: 3.5rem; width: 100%;"></div>
                        <div class="card-title text-truncate"  style="background-color: rgba(86, 189, 190, 0.5); font-size:calc(12px + 1vw); padding: 3vw 0; width: 100%;">{{ value.title }}</div>
                        <div class="text-truncate" style="font-size:calc(8px + 1vw); padding: 1vw 0 0;">평점: {{ value.vote_average }}</div>
                      </div>
                    </div>

                  </div> 
                 
                {% endfor %}
              </div>
            </div>
            

        {% endif %}
      {% endfor %}
      
      
      <p></p>
    {% endfor %}
  {% else %}
  <div class="text-center mt-5">
    <h1>선호하는 영화 장르가 존재하지 않습니다...</h1>
    <h2>'나의 프로필'에서 선호하는 영화 장르를 1개 이상 체크하거나, 좋아하는 영화에 높은 별점을 체크해주세요!</h2>
    <img src="../../photo/lion.gif" width="600">
  </div>
  {% endif %}
  <style media="screen">
   .wrap{
     width: 1300px;
     height: 600px;
     overflow-x: scroll;
     white-space:nowrap
   }
   .wrap img{
       width:300px;
       height:100%;
   }
  .b-panel::after {
    content: "\f107";
    color: #333;
    right: 10px;
    position: absolute;
      font-family: "FontAwesome"
  }

  .b-panel[aria-expanded="true"]::after {
    content: "\f106";
  }

  .imageDiv {
    z-index: 1;
  }

  .card:hover .imageDiv {
    z-index: 0;
    opacity: 0.3;

  }

  .card {
    transition: transform .3s;
  }

  .card:hover {
    transform: scale(1.1);
  }
</style>

<script>

  for (var img of document.getElementsByClassName("poster-img")) {
    if (img.src.slice(31, img.src.length).indexOf('/') !== 0) {
      img.src = img.src.slice(31, img.src.length)
    }
  }


  const likeBtns = document.querySelectorAll('.like-btn')
  likeBtns.forEach(function (btn) {
    btn.addEventListener('mouseover', function (event) {
      btn.getElementsByTagName('i')[0].classList.add('animate__animated', 'animate__rubberBand')

    })
    btn.addEventListener('mouseout', function (event) {
      btn.getElementsByTagName('i')[0].classList.remove('animate__animated', 'animate__rubberBand')

    })
    btn.addEventListener('click', function (event) {
      axios.get(`/movies/${btn.dataset.pk}/like`)
        .then(function (res) {
          if (res.data.liked) {
            btn.getElementsByTagName('i')[0].style.color = 'crimson'
          } else {
            btn.getElementsByTagName('i')[0].style.color = 'white'
          }

        })
        .catch(function (err) {
          console.log(err)
        })
    })
  })
  function getOffsetTop(el) {
    var top = 0;
    if (el.offsetParent) {
      do {
        top += el.offsetTop;
      } while (el = el.offsetParent);
      return [top];
    }
  }
  window.scrollTo({top: getOffsetTop(document.getElementById("bookmark")), behavior:'smooth'});

</script>



{% endblock %}