accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:pk>/follow', views.follow, name='follow'),
    path('<username>/<int:pk>/<int:id>/', views.prefer, name='prefer'),
    
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    date_joined = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(auto_now_add=True)

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    # related_name : 역참조시 이름 바꿈



class User_genre(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like_genres = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_genres", blank=True)
    like_genres_count = models.PositiveIntegerField(default=0)
    ids = [
    {
        "id": 10770,
        "name": "TV 영화",
        "isprefer": False
    },
    {
        "id": 10752,
        "name": "전쟁",
        "isprefer": False
    },
    {
        "id": 10751,
        "name": "가족",
        "isprefer": False
    },
    {
        "id": 10749,
        "name": "로맨스",
        "isprefer": False
    },
    {
        "id": 10402,
        "name": "음악",
        "isprefer": False
    },
    {
        "id": 9648,
        "name": "미스터리",
        "isprefer": False
    },
    {
        "id": 878,
        "name": "SF",
        "isprefer": False
    },
    {
        "id": 99,
        "name": "다큐멘터리",
        "isprefer": False
    },
    {
        "id": 80,
        "name": "범죄",
        "isprefer": False
    },
    {
        "id": 53,
        "name": "스릴러",
        "isprefer": False
    },
    {
        "id": 37,
        "name": "서부",
        "isprefer": False
    },
    {
        "id": 36,
        "name": "역사",
        "isprefer": False
    },
    {
        "id": 35,
        "name": "코미디",
        "isprefer": False
    },
    {
        "id": 28,
        "name": "액션",
        "isprefer": False
    },
    {
        "id": 27,
        "name": "공포",
        "isprefer": False
    },
    {
        "id": 18,
        "name": "드라마",
        "isprefer": False
    },
    {
        "id": 16,
        "name": "애니메이션",
        "isprefer": False
    },
    {
        "id": 14,
        "name": "판타지",
        "isprefer": False
    },
    {
        "id": 12,
        "name": "모험",
        "isprefer": False
    },
    ]

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('last_name', 'first_name', 'email',)
        

accounts/views.py
# Create your views here.
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, redirect, render
from accounts.forms import CustomUserCreationForm
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout
from .models import User_genre
from .genre_id import GENRE

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }

    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('main:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('main:index')


def profile(request, username):
    User = get_user_model()
    profile_user = get_object_or_404(User, username=username)
    genres = GENRE
    usergenre = User_genre
    context = {
        'profile_user' : profile_user,
        'genres' : genres,
        'usergenre' : usergenre,
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, pk):
    User = get_user_model()
    me = request.user
    you = get_object_or_404(User, pk=pk)
    if me in you.followers.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)
    return redirect('accounts:profile', you.username)


# follow() got an unexpected keyword argument 'username'
# typeerror - pk가 와야하는데 username들어옴
# 'User' object has no attribute 'followers'
def prefer(request, username, pk, id):
    genre = User_genre.like_genres
    
    tmd = username
    User = get_user_model()
    profile_user = get_object_or_404(User, username=username)
    
    # for i in range(len(genre)):
    #     if genre[i]['id'] == id:
    #         if genre[i]['isprefer'] == True:
    #             genre[i]['isprefer'] = False
    #         else:
    #             genre[i]['isprefer'] = True
    
    print(pk)
    if id in profile_user.like_genres.all():
        profile_user.like_genres.remove(id)
        profile_user.save()
    else:
        profile_user.like_genres.add(id)
        profile_user.save()
    
    
    
    return redirect('accounts:profile', profile_user.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary">
</form>

{% endblock body %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
{% comment %} 🐹 {% endcomment %}
<div class="container mt-5">
<h1 class="mt-5, ml-5">{{ profile_user.username }} 님의 프로필 페이지</h1>
<div class="d-flex align-items-center">
<p style="margin:3.5rem; margin-left:0;">팔로워: {{ profile_user.followers.all|length }} | 팔로우: {{ profile_user.followings.all|length }} </p>
{% if user != profile_user %}
<form action="{% url 'accounts:follow' profile_user.pk %}" method="POST">
  {% csrf_token %}
  {% if user in profile_user.followers.all %}
    <input type="submit" value="unfollow"s tyle="margin:2rem 0;" class="btn"
    style="color: #ab36cf; background-color: #fff; border-color: #ab36cf;">
  {% else %}
    <input type="submit" value="follow"s tyle="margin:2rem 0;" class="btn"
    style="color: #fff; background-color: #ab36cf; border-color: #ab36cf;">
  {% endif %}
</form>
{% endif %}
</div>
</div>
  
    {% comment %} {% if usergenre.id_10770 == True %}
      <button type="submit" class="btn btn-info btn-lg" id="inlineCheckbox{{ids.id}}" autocomplete="on">
      {{usergenre.id_10770}}</button>
    {% else %}
      <button type="submit" class="btn btn-light btn-lg" id="inlineCheckbox{{ids.id}}" autocomplete="on">
      {{usergenre.id_10770}}</button>
    {% endif %} {% endcomment %}

  {% comment %} <div class="row m-0 my-5 row-cols-1 row-cols-md-6 g-3">
    {% for ids in usergenre.ids %} 
      <form action="{% url 'accounts:prefer' profile_user.username profile_user.id ids.id %}" method="post">
        {% csrf_token %}
        {% if ids.isprefer == True %}
          <button type="submit" class="btn btn-info btn-lg" id="inlineCheckbox{{ids.id}}" autocomplete="on">
          {{ids.name}}</button>
        {% else %}
          <button type="submit" class="btn btn-light btn-lg" id="inlineCheckbox{{ids.id}}" autocomplete="on">
          {{ids.name}}</button>
        {% endif %}
      </form>
    {% endfor %}
  </div> {% endcomment %}
  {% if user == profile_user %}
    {% include '../community/choose.html' %}
  {% endif %}
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary">
</form>

{% endblock body %}