accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:pk>/follow', views.follow, name='follow'),
    path('<username>/<int:pk>/<int:id>/', views.prefer, name='prefer'),
    
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/comment/create/', views.comments_create, name='comments_create'),
    path('onair/', views.onair, name='onair'),
    path('recommend/', views.recommend, name="recommend"),
    path('choose/', views.choose, name="choose"),
    path('likechoose/<username>/<int:id>/', views.like_choose, name="like_choose"),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    # path('choose/<username>/<int:pk>/<int:id>/', views.choose, name='choose'),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/my_vote', views.my_vote, name='my_vote'),
]

muje/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_nav.html
<nav class="navbar navbar-expand-lg" style="padding: 0.4rem 0.4rem; background: #3a3636; font-family: 'ONE-Mobile-POP';">
<div class="container-fluid">
  <a class="navbar-brand" href="{% url 'main:index' %}">
    <img src="../../photo/Muje2.gif" alt="" width="150" >
  </a>
  {% comment %} <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> {% endcomment %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    {% comment %} <div class="navbar-nav"> {% endcomment %}
      <ul class="navbar-nav fs-5 me-auto mb-lg-0">
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'community:onair' %}">현재 상영중</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'community:index'%}">커뮤니티</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'movies:index' %}">영화 전체목록</a>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile' user.username %}">Profile</a>
      </li> {% endcomment %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'community:recommend' %}">추천영화</a>
      </li>
      </ul>
      <ul class="navbar-nav navbar-right fs-5 ml-auto">
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'community:choose' %}">나의 프로필</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      </ul>
      
      {% else %}
      </ul>
      <ul class="navbar-nav navbar-right fs-5 ml-auto">
      <li class="nav-item ">
        <a class="nav-link text-white" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      {% endif %}
    </ul>
    {% comment %} </div> {% endcomment %}
  </div>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
  <style>
    @font-face {
      font-family: 'BMEuljiro10yearslater';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/BMEuljiro10yearslater.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }
    @font-face {
      font-family: 'KoPubDotumMedium';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/KoPubDotumMedium.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }
    @font-face {
      font-family: 'ONE-Mobile-POP';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/ONE-Mobile-POP.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }
    @font-face {
      font-family: 'KOTRALEAP';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2110@1.0/KOTRALEAP.woff2') format('woff2');
      font-weight: normal;
      font-style: normal;
    }
    
  </style>
</head>
<body style="background:black" class="text-white">
  {% include '_nav.html' %}
  {% block body %}
  {% endblock body %}
  </div>
  
  <!-- JavaScript Bundle with Popper -->
  <script src="https://kit.fontawesome.com/e87731a046.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>